### PR TITLE
Modularization

### PR DESCRIPTION
**Pull request by miguel-guedes**
A first effort towards modularization of Sorting Desk.

Please do not upload to Chrome store yet.

### CODE REVIEW

**Comment by jsonjunky** [comment]
Hi Miguel,
   Trying to build it for chrome on linux.
I did the npm install .

Then I tried:

darren@ganymede:~/sortingdesk$ make all
I: running all tests
E: chromedriver not found
make: *** [test-extensions] Error 1
darren@ganymede:~/sortingdesk$

Are there build instructions for chrome? I see the firefox ones.


On Thu, Jun 25, 2015 at 7:06 AM, Miguel Guedes <notifications@github.com>
wrote:

> A first effort towards modularization of Sorting Desk.
>
> Please do not upload to Chrome store yet.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/dossier/sortingdesk/pull/9
> Commit Summary
>
>    - sorting-desk: first effort at modularization
>    - extensions: support modular Sorting Desk
>    - sorting-queue: use global jshint settings
>    - extensions: update dependencies
>
> File Changes
>
>    - *M* sh/update-deps
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-0> (14)
>    - *A* src/.jshintrc
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-1> (3)
>    - *M*
>    src/browser/extensions/chrome/lib/sorting-common/sorting_common.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-2> (4)
>    - *A*
>    src/browser/extensions/chrome/lib/sorting-desk/explorer/controller.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-3> (696)
>    - *A*
>    src/browser/extensions/chrome/lib/sorting-desk/explorer/deferred.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-4> (187)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/explorer/dnd.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-5> (182)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/explorer/folder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-6> (181)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/explorer/item.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-7> (410)
>    - *A*
>    src/browser/extensions/chrome/lib/sorting-desk/explorer/itembase.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-8> (163)
>    - *A*
>    src/browser/extensions/chrome/lib/sorting-desk/explorer/subfolder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-9> (286)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/facets.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-10> (209)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-11> (215)
>    - *M* src/browser/extensions/chrome/lib/sorting-desk/sorting_desk.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-12> (2457)
>    - *M* src/browser/extensions/chrome/lib/sorting-desk/translation.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-13> (37)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/ui/css.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-14> (35)
>    - *A* src/browser/extensions/chrome/lib/sorting-desk/ui/failure.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-15> (65)
>    - *M* src/browser/extensions/chrome/lib/sorting-queue/sorting_queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-16> (4)
>    - *M* src/browser/extensions/chrome/src/html/sidebar.html
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-17> (11)
>    - *M* src/browser/extensions/chrome/src/js/sidebar.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-18> (6)
>    - *M*
>    src/browser/extensions/firefox/data/lib/sorting-common/sorting_common.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-19> (4)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/controller.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-20> (696)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/deferred.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-21> (187)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/dnd.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-22> (182)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/folder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-23> (181)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/item.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-24> (410)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/itembase.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-25> (163)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/explorer/subfolder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-26> (286)
>    - *A* src/browser/extensions/firefox/data/lib/sorting-desk/facets.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-27> (209)
>    - *A* src/browser/extensions/firefox/data/lib/sorting-desk/queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-28> (215)
>    - *M*
>    src/browser/extensions/firefox/data/lib/sorting-desk/sorting_desk.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-29> (2457)
>    - *M*
>    src/browser/extensions/firefox/data/lib/sorting-desk/translation.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-30> (37)
>    - *A* src/browser/extensions/firefox/data/lib/sorting-desk/ui/css.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-31> (35)
>    - *A*
>    src/browser/extensions/firefox/data/lib/sorting-desk/ui/failure.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-32> (65)
>    - *M*
>    src/browser/extensions/firefox/data/lib/sorting-queue/sorting_queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-33> (4)
>    - *M* src/browser/extensions/firefox/data/src/html/sidebar.html
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-34> (11)
>    - *M* src/browser/extensions/firefox/data/src/js/sidebar.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-35> (2)
>    - *M* src/sorting-common/sorting_common.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-36> (4)
>    - *A* src/sorting-desk/explorer/controller.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-37> (696)
>    - *A* src/sorting-desk/explorer/deferred.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-38> (187)
>    - *A* src/sorting-desk/explorer/dnd.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-39> (182)
>    - *A* src/sorting-desk/explorer/folder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-40> (181)
>    - *A* src/sorting-desk/explorer/item.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-41> (410)
>    - *A* src/sorting-desk/explorer/itembase.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-42> (163)
>    - *A* src/sorting-desk/explorer/subfolder.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-43> (286)
>    - *A* src/sorting-desk/facets.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-44> (209)
>    - *A* src/sorting-desk/queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-45> (215)
>    - *M* src/sorting-desk/sorting_desk.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-46> (2457)
>    - *M* src/sorting-desk/translation.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-47> (37)
>    - *A* src/sorting-desk/ui/css.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-48> (35)
>    - *A* src/sorting-desk/ui/failure.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-49> (65)
>    - *M* src/sorting-queue/sorting_queue.js
>    <https://github.com/dossier/sortingdesk/pull/9/files#diff-50> (4)
>
> Patch Links:
>
>    - https://github.com/dossier/sortingdesk/pull/9.patch
>    - https://github.com/dossier/sortingdesk/pull/9.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dossier/sortingdesk/pull/9>.
>



-- 
Darren Govoni
703.738.6797 (land)
703.899.6491 (air)

**Comment by BurntSushi** [comment]
> Hi Miguel,
> Trying to build it for chrome on linux.
> I did the npm install .
>
> Then I tried:
>
> darren@ganymede:~/sortingdesk$ make all
> I: running all tests
> E: chromedriver not found
> make: *** [test-extensions] Error 1
> darren@ganymede:~/sortingdesk$
>
> Are there build instructions for chrome? I see the firefox ones.

You should not need to run `make` to do development on the extension in Chrome.

Instead, please load the extension as an unpacked extension. There is
a button for it in the "extensions" config in your browser. You will
need to tick "developer mode" before this option becomes available.

(Running tests requires a Selenium installation. I do not recommend
you trying to set that up.)

**Comment by BurntSushi** [comment]
>> Hi Miguel,
>> Trying to build it for chrome on linux.
>> I did the npm install .
>>
>> Then I tried:
>>
>> darren@ganymede:~/sortingdesk$ make all
>> I: running all tests
>> E: chromedriver not found
>> make: *** [test-extensions] Error 1
>> darren@ganymede:~/sortingdesk$
>>
>> Are there build instructions for chrome? I see the firefox ones.
>
> You should not need to run `make` to do development on the extension in Chrome.
>
> Instead, please load the extension as an unpacked extension. There is
> a button for it in the "extensions" config in your browser. You will
> need to tick "developer mode" before this option becomes available.
>
> (Running tests requires a Selenium installation. I do not recommend
> you trying to set that up.)

With that said, here's some more info that you may find useful.

For better or worse, we vendor our Javascript dependencies. (This
means we commit our dependencies to the repository.) In particular, we
vendor *both* external dependencies like jquery and internal
dependencies like SortingQueue. At some point, we'd like to migrate to
a Javascript package manager, but it hasn't been prioritized yet.

On top of that, and for reasons I've since forgotten, Chrome expects
its files to be in a certain hierarchy. So when you make changes, you
do actually need to run `make deps`, which copies files from
`./src/sorting-*` into their appropriate locations inside
`./src/browser`.

My hope is that you shouldn't have to dig into the SortingDesk code
for this task. But if you do, please be aware that Javascript files in
a `lib` directory are generally vendored.

- Andrew

**Comment by jsonjunky** [comment]
Yeah, I don't think I'll need to get into the SD code. Per my other email
its running.
But I am trying to add a subfolder and it adds in the UI but is not
persistent. When I refresh, its gone.
I set a breakpoint on the add subfolder route and its not getting called.
No debug info on the javascript console.

When the subfolder appears in SD I click the cloud button and it does hit
the subfolder/extract route in dossier.models (still not sure why there are
SD routes in models and in web and I run the web wsgi).

Since someone else wrote those route stubs and put their task items in it I
will try to figure out the next steps.



On Mon, Jun 29, 2015 at 10:15 AM, Andrew Gallant <notifications@github.com>
wrote:

> >> Hi Miguel,
> >> Trying to build it for chrome on linux.
> >> I did the npm install .
> >>
> >> Then I tried:
> >>
> >> darren@ganymede:~/sortingdesk$ make all
> >> I: running all tests
> >> E: chromedriver not found
> >> make: *** [test-extensions] Error 1
> >> darren@ganymede:~/sortingdesk$
> >>
> >> Are there build instructions for chrome? I see the firefox ones.
> >
> > You should not need to run `make` to do development on the extension in
> Chrome.
> >
> > Instead, please load the extension as an unpacked extension. There is
> > a button for it in the "extensions" config in your browser. You will
> > need to tick "developer mode" before this option becomes available.
> >
> > (Running tests requires a Selenium installation. I do not recommend
> > you trying to set that up.)
>
> With that said, here's some more info that you may find useful.
>
> For better or worse, we vendor our Javascript dependencies. (This
> means we commit our dependencies to the repository.) In particular, we
> vendor *both* external dependencies like jquery and internal
> dependencies like SortingQueue. At some point, we'd like to migrate to
> a Javascript package manager, but it hasn't been prioritized yet.
>
> On top of that, and for reasons I've since forgotten, Chrome expects
> its files to be in a certain hierarchy. So when you make changes, you
> do actually need to run `make deps`, which copies files from
> `./src/sorting-*` into their appropriate locations inside
> `./src/browser`.
>
> My hope is that you shouldn't have to dig into the SortingDesk code
> for this task. But if you do, please be aware that Javascript files in
> a `lib` directory are generally vendored.
>
> - Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dossier/sortingdesk/pull/9#issuecomment-116690871>.
>



-- 
Darren Govoni
703.738.6797 (land)
703.899.6491 (air)

**Comment by miguel-guedes** [comment]
On 29/06/15 15:15, Andrew Gallant wrote:
> On top of that, and for reasons I've since forgotten, Chrome expects
>  its files to be in a certain hierarchy.

IIRC, the problem was that we couldn't simply symlink to the
dependencies and had to instead manually copy the files whenever any
changed; Chrome doesn't support (or allow) symlinks in extensions.

> So when you make changes, you do actually need to run `make deps`, 
> which copies files from `./src/sorting-*` into their appropriate 
> locations inside `./src/browser`.

I've not had the time to develop a better solution for this in Python
but there is a bash script in `./sh` called `watch-deps` that uses the
utility `inotifywait` [0] to automatically update dependencies whenever
changes happen inside the `./src` subtree.

> My hope is that you shouldn't have to dig into the SortingDesk code 
> for this task. But if you do, please be aware that Javascript files 
> in a `lib` directory are generally vendored.

This is true with an exception: for whatever reason, Mozilla decided
that Firefox extensions *must* have a `lib` directory *and* a `main.js`
(equivalent to Chrome's `background.js`) source file inside it [1].
Thus, `lib` in this case means something else.  The dependencies of the
Firefox extension can be found in `./data/lib` (from the extension's
root directory).

[0] http://linux.die.net/man/1/inotifywait
[1]
https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Module_structure_of_the_SDK#Local_Modules

**Pull request merged**
